name: Build

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macOS-latest]

    steps:
      - name: Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Decrypt secret
        run: ./.github/scripts/decrypt_secret.sh
        env:
          BUILD_KEY: ${{ secrets.BUILD_KEY }}
          BUILD_IV: ${{ secrets.BUILD_IV }}
          BUILD_PASS: ${{ secrets.BUILD_PASS }}
      - name: npm install
        run: |
          npm install
      - name: npm build
        run: |
          npm run build
      - name: electron build
        run: |
          npm run dist -- -lwm
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

