name: Release

on:
  push:
    tags:
      - v*

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macOS-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Decrypt secret
        run: ./.github/scripts/decrypt_secret.sh
        env:
          BUILD_KEY: ${{ secrets.BUILD_KEY }}
          BUILD_IV: ${{ secrets.BUILD_IV }}
          BUILD_PASS: ${{ secrets.BUILD_PASS }}
      - name: Build App
        run: |
          npm install
          npm run build
          npm run dist
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/TistoryEditor-*.exe
            dist/TistoryEditor-*.deb
            dist/TistoryEditor-*.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

